#Copy SSH keys from windows to WSL
- name: Load env variables for username/password
  include_vars:
    file: "../../../../.env.yml"
    name: env_vars


- name: Ensure .ssh directory exists
  file: 
    path: "~/.ssh"
    state: directory
    mode: 0700

- name: Copy private key from Window
  copy:
    src: "{{ env_vars.Private_key_path }}"
    dest: "~/.ssh/id_ed25519"
    mode: '0600'

- name: Copy public key from Window
  copy:
    src: "{{ env_vars.Public_key_path }}"
    dest: "~/.ssh/id_ed25519.pub"
    mode: '0644'
    
- name: Display success
  debug:
    msg: "SSH keys have been copied successfully!"