- name: Install Socat
  apt:
    name:
      - socat
    state: present
  retries: 5
  delay: 10
  register: apt_result
  until: apt_result is succeeded

- name: Creating socat proxy
  shell: socat TCP-LISTEN:9091,bind=172.17.0.1,reuseaddr,fork TCP:127.0.0.1:9091 &

